# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "T430"
  config.vm.synced_folder "jenkinsHome/", "/home/vagrant/jenkinsHome",
  id: "jenkins"
  config.vm.synced_folder "ansible/", "/home/vagrant/ansible",
  id: "ansible"
  config.vm.network "public_network", ip: "192.168.0.134"

  
  #To improve the internet speed within VirtualBox machine. Link reference: https://github.com/hashicorp/vagrant/issues/1807#issuecomment-19132198
  config.vm.provider :virtualbox do |vb|
    #vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    #vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.memory = "2048"
    
  end

  config.vm.provision "shell" do |s|
  ssh_prv_key = ""
  ssh_pub_key = ""
  if File.file?("#{Dir.home}/.ssh/id_rsa")
    ssh_prv_key = File.read("#{Dir.home}/.ssh/id_rsa")
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  else
    puts "No SSH key found. You will need to remedy this before pushing to the repository."
  end
  s.inline = <<-SHELL
    if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
      echo "SSH keys already provisioned."
      exit 0;
    fi
    echo "SSH key provisioning."
    mkdir -p /home/vagrant/.ssh/
    touch /home/vagrant/.ssh/authorized_keys
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    echo #{ssh_pub_key} > /home/vagrant/.ssh/id_rsa.pub
    chmod 644 /home/vagrant/.ssh/id_rsa.pub
    echo "#{ssh_prv_key}" > /home/vagrant/.ssh/id_rsa
    chmod 600 /home/vagrant/.ssh/id_rsa
    chown -R vagrant:vagrant /home/vagrant
    exit 0
  SHELL
end
  
	#To provision with external shell script:
  config.vm.provision "shell", path: "UpdateUbuntu.sh"
  config.vm.provision "shell", path: "InstallJava.sh"
  config.vm.provision "shell", path: "InstallJenkins.sh"

  config.vm.network :forwarded_port, guest: 8040, host: 8040
  config.vm.network :forwarded_port, guest: 8080, host: 8060

end
