# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "hashicorp/bionic64"
  config.vm.hostname = "jenkins"
  config.vm.synced_folder "jenkinsHome/", "/home/vagrant/jenkinsHome",
  id: "jenkins"
  config.vm.network "public_network", ip: "192.168.0.134"

  
  #To improve the internet speed within VirtualBox machine. Link reference: https://github.com/hashicorp/vagrant/issues/1807#issuecomment-19132198
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.memory = "2048"
    
  end
  
	#To provision with external shell script:
  config.vm.provision "shell", path: "UpdateUbuntu.sh"
  config.vm.provision "shell", path: "InstallJava.sh"
  config.vm.provision "shell", path: "InstallJenkins.sh"

  config.vm.network :forwarded_port, guest: 8040, host: 8040
  config.vm.network :forwarded_port, guest: 8080, host: 8060

end
