# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "hashicorp/bionic64" 
  config.vm.box = "ubuntu18_Java8_Base"
  config.vm.hostname = "Ansible"
  config.vm.synced_folder "ansibleScripts/", "/home/vagrant/ansibleScripts",
  id: "ansible"
  config.vm.network "public_network", ip: "192.168.0.135"
  
  #To improve the internet speed within VirtualBox machine. Link reference: https://github.com/hashicorp/vagrant/issues/1807#issuecomment-19132198
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.memory = "1024"
    
  end
  
end