# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu18_Java8_Base"

  config.vm.hostname = "tomcat"
  config.vm.synced_folder "tomcat/", "/home/vagrant/tomcat",
  id: "tomcat"
  config.vm.network "public_network", ip: "192.168.0.136"
  
  #To improve the internet speed within VirtualBox machine. Link reference: https://github.com/hashicorp/vagrant/issues/1807#issuecomment-19132198
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.memory = "1024"
    
  end
  config.vm.provision "shell", path: "InstallAndConfigureTomcat.sh"
end
